Update dutch translations
leonlatsch/Photok pull request #235
Opened 2023-11-28 22:23 UTC by GJteVelde

**Description:**

Updated dutch translations

**Tasks:**
- [ ] Build CI Runs
- [ ] Code Analysis up to standards

2023-11-28 22:54 UTC, leonlatsch requested changes

2023-11-28 22:54 UTC, leonlatsch commented on app/src/main/res/values-nl/strings.xml
> +    <string name="import_menu_photos">Foto\'s/string>
You accidentally removed a <

2023-11-29 06:03 UTC, GJteVelde commented on app/src/main/res/values-nl/strings.xml
> +    <string name="import_menu_photos">Foto\'s/string>
Fixed it :)

2023-11-29 09:09 UTC, leonlatsch approved these changes

2023-11-29 09:10 UTC, merged