Add option to delete files after export #247
leonlatsch/Photok pull request #259
Opened 2024-02-21 11:25 UTC by BIBLETUM

**Description:**

*Add option to delete files after export*

**Tasks:**
- [ ] Add option to delete files after export to settings layout
- [ ] Add option to delete files after export on ImageViewFragment
- [ ]  Add option to delete files after export on GalleryFragment
- [ ] Translate all new strings

2024-02-21 13:32 UTC, leonlatsch requested changes

2024-02-21 13:32 UTC, leonlatsch commented on app/src/main/java/dev/leonlatsch/photok/imageviewer/ui/ImageViewerViewModel.kt
> +            photoRepository.exportPhoto(currentPhoto!!).let {
name "it" as "success"

2024-02-21 13:32 UTC, leonlatsch commented on app/src/main/res/values-de/strings.xml
> +    <string name="export_and_delete_are_you_sure_this">Sind Sie sicher, dass Sie diese Datei in Ihre Galerie <b>exportieren</b> und löschen möchten?</string>
In german we use "du" and here are some grammar issues

2024-02-21 13:32 UTC, leonlatsch commented on app/src/main/res/values-de/strings.xml
> +    <string name="export_and_delete_are_you_sure_this">Sind Sie sicher, dass Sie diese Datei in Ihre Galerie <b>exportieren</b> und löschen möchten?</string>
Also, please don't use google translate for these translations. Add the english with a <!-- TODO --> in order for the badges in the README to work.

2024-02-21 14:37 UTC, leonlatsch requested changes
Very nice, BUT the message for exporting multiple images still needs to be adjusted. Its enough to do it for the new gallery and not the old one

2024-02-21 14:38 UTC, leonlatsch commented
@BIBLETUM and maybe you can find other icons for these options. Hard to imagine but maybe you find something in the assets of android studio. If not its ok to leave ic_delete for both

2024-02-22 07:47 UTC, BIBLETUM commented
Unfortunately could not find any other matching icons

2024-02-22 07:55 UTC, leonlatsch approved these changes
👍

2024-02-22 08:52 UTC, leonlatsch commented on app/src/main/res/values-es/strings.xml
> -    <string name="recovery_subtitle_reset_hide_app">Reset Hide App Setting</string> <!-- TODO -->
this TODO needs to stay

2024-02-22 09:47 UTC, merged